### ISSUE TITLE
how to change the homepage from localhost:10080 to gitlab.myhome.com?

### ISSUE THREAD

**Issue by rubinliudongpo** [bravist/gitlab-docker#3]
I tried to change the configuration in .env to
`GITLAB_HOST=gitlab.example.com
GITLAB_PORT=80
GITLAB_SSH_PORT=10022`
and added a server in Nginx config file, while it does not work.
Please give me some help, Thanks.

**Comment by huiyonghkw** [comment]
first,  make sure  set up `GITLAB_HOST = gitlab.myhome.com` 

second,  use ```bash $ ping gitlab.myhome.com```

to get the ip. `gitlab-ci-docker` has built in Nginx , you do not config other nginx.


three.  if localhost, please config the /etc/host

```bash

127.0.0.1 gitlab.myhome.com 
```
and visit gitlab.myhome.com and make sure the port 80 is  not used by others
